# Generated by Django 5.1.3 on 2024-11-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
