# Generated by Django 5.1.3 on 2024-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_restaurant_staff_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
